name: Surge
favicon: null
layout_spectrum: 0.50471
typography_spectrum: 1
title: Surge Labs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfcf3'
    - '#fe4047'
    - '#fdc1a4'
    - '#97545e'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
