name: Surge
favicon: null
layout_spectrum: 0.50471
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
